name: tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
          check-latest: true
          cache: true
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout 3m0s
  unit:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
          check-latest: true
          cache: true
      - name: Run tests
        run: make test
  e2e:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cni: [iptables, ipvs, cilium]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
          check-latest: true
          cache: true
      - name: Run e2e
        run: make e2e CNI=${{ matrix.cni }}
  helm-docs:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
          check-latest: true
          cache: true
      - name: Run helm-docs
        run: make helm-docs
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git diff
            echo 'run make helm-docs and commit changes'
            exit 1
          fi
